version: 2
executorType: docker
containerInfo:
  - image: tsloughter/erlang-git:19.2
    cmd: ["/bin/bash"]
stages:
  build:
    workDir: ~/vonnegut
    steps:
      - type: checkout

      - type: cache-restore
        key: vonnegut-{{ .Branch }}-{{ checksum "rebar.lock" }}

      - type: cache-restore
        key: erlang-plt-19.2

      - type: cache-restore
        key: hex-packages

      - type: shell
        shell: /bin/bash
        command: |
            set -exu

            rebar3 do dialyzer, xref, ct, cover
            rebar3 coveralls send

            mkdir -p junit/
            mv _build/test/logs/ct_run*/junit_report.xml junit/

      - type: test-results-store
        path: ~/vonnegut/junit

      - type: artifacts-store
        path: ~/vonnegut/_build/test/logs
        destination: common_test

      - type: cache-save
        key: vonnegut-{{ .Branch }}-{{ checksum "rebar.lock" }}
        paths:
          - ~/vonnegut/_build/default/lib
          - ~/vonnegut/_build/default/plugins

      - type: cache-save
        key: erlang-plt-19.2
        paths:
          - ~/.cache/rebar3/rebar3_19.2_plt

      - type: cache-save
        key: hex-packages
        paths:
          - ~/.cache/rebar3/hex/default/packages
