version: 2
executorType: docker
containerInfo:
  - image: tsloughter/erlang-git:19.2
    cmd: ["/bin/bash"]
stages:
  build:
    workDir: ~/vonnegut
    steps:
      - type: checkout

      - type: shell
        shell: /bin/bash
        command: |
            set -exu

            rebar3 do dialyzer, xref, ct, cover
            rebar3 coveralls send
