steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: ['-c', 'docker build -t us.gcr.io/$PROJECT_ID/vonnegut:$$(git describe --abbrev=4 HEAD --tags) .']
images: ['us.gcr.io/nucleus-sti/vonnegut']
