defaults: &defaults
  shell: /bin/bash
  working_directory: /home/circleci/vonnegut
  docker:
    - image: tsloughter/erlang-alpine:20.1.4
      cmd: ["/bin/bash"]

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - vonnegut-{{ checksum "rebar.lock" }}
            - vonnegut-hex-packages

      - run:
          command: rebar3 compile

      - store_artifacts:
          path: /home/circleci/vonnegut/rebar3.crashdump
          destination: rebar3_crashdump.txt
          when: on_fail

      - save-cache:
          key: vonnegut-{{ checksum "rebar.lock" }}
          paths:
            - /home/circleci/vonnegut/_build/default/lib
            - /home/circleci/vonnegut/_build/default/plugins

      - save-cache:
          key: vonnegut-hex-packages
          paths:
            - /root/.cache/rebar3/hex/default/packages

  dialyzer:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /home/circleci/vonnegut

      - restore_cache:
          keys:
            - erlang-plt-20.0.1

      - restore_cache:
          keys:
            - vonnegut-{{ checksum "rebar.lock" }}
            - vonnegut-hex-packages

      - run:
          command: rebar3 dialyzer

      - save-cache:
          key: erlang-plt-20.0.1
          paths:
            - /root/.cache/rebar3/rebar3_20.0.1_plt
  xref:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /home/circleci/vonnegut

      - restore_cache:
          keys:
            - vonnegut-{{ checksum "rebar.lock" }}
            - vonnegut-hex-packages

      - run:
          command: rebar3 xref

  tests:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /home/circleci/vonnegut

      - restore_cache:
          keys:
            - vonnegut-{{ checksum "rebar.lock" }}
            - vonnegut-hex-packages

      - run:
          command: |
            set -eux
            rebar3 do ct --name=testrunner@127.0.0.1, cover
            rebar3 coveralls send

      - store_test_results:
          path: /home/circleci/vonnegut/_build/test/logs/

      - store_artifacts:
          path: /home/circleci/vonnegut/_build/test/logs
          destination: common_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - dialyzer:
          requires:
            - build
      - xref:
          requires:
            - build
      - tests:
          requires:
            - build
