apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-vonnegut-config"
data:
  vonnegut.discovery_domain: "_partisan._tcp.{{ .Values.service.name }}.default.svc.cluster.local"
  vonnegut.replicas: "{{ .Values.replicaCount }}"
