apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
    type: service
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: data
  - port: {{ .Values.service.partisanPort }}
    targetPort: {{ .Values.service.partisanPort }}
    protocol: TCP
    name: partisan
  selector:
    app: {{ template "fullname" . }}
    type: node
